name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Golang / Ubuntu
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: "^1.16"
      - run: go test ./...
